// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOOp7igKacUAldEqW_gBUSIJ7pqSjJS6U',
    appId: '1:585034094277:web:008f6cc30de91b5a4582ac',
    messagingSenderId: '585034094277',
    projectId: 'gridscout-c084c',
    authDomain: 'gridscout-c084c.firebaseapp.com',
    storageBucket: 'gridscout-c084c.appspot.com',
    measurementId: 'G-P8CH4MVPZ7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBX7r9CCDUFLmNxKaXarXTDhZrBtEamb54',
    appId: '1:585034094277:android:578fa1c566364d6c4582ac',
    messagingSenderId: '585034094277',
    projectId: 'gridscout-c084c',
    storageBucket: 'gridscout-c084c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArE0SbWWGE6d-h6xOeKter0niS91GR3Io',
    appId: '1:585034094277:ios:d310783444d765a24582ac',
    messagingSenderId: '585034094277',
    projectId: 'gridscout-c084c',
    storageBucket: 'gridscout-c084c.appspot.com',
    iosBundleId: 'com.example.asugs',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyArE0SbWWGE6d-h6xOeKter0niS91GR3Io',
    appId: '1:585034094277:ios:d310783444d765a24582ac',
    messagingSenderId: '585034094277',
    projectId: 'gridscout-c084c',
    storageBucket: 'gridscout-c084c.appspot.com',
    iosBundleId: 'com.example.asugs',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDOOp7igKacUAldEqW_gBUSIJ7pqSjJS6U',
    appId: '1:585034094277:web:01982f749a18fcc44582ac',
    messagingSenderId: '585034094277',
    projectId: 'gridscout-c084c',
    authDomain: 'gridscout-c084c.firebaseapp.com',
    storageBucket: 'gridscout-c084c.appspot.com',
    measurementId: 'G-DXJ0VQMQBJ',
  );

}